### ISSUE TITLE
Builder.py throwing error

### ISSUE THREAD

**Issue by sp00kyhacker** [Pure-L0G1C/Loki#11]
Traceback (most recent call last):
  File "G:\R\RR\Loki-master\builder\builder.py", line 14, in <module>
    from lib.aes import CryptoAES
  File "G:\R\RR\Loki-master\builder\lib\aes.py", line 5, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

I am getting this error, I've tried to manually do pip install pycrypto to see if that helped and it did not.

**Comment by Pure-L0G1C** [comment]
```bash
$> pip install pycryptodome
```

**Comment by sp00kyhacker** [comment]
This solved my problem, thanks for the support!
