### ISSUE TITLE
cannot import name const

### ISSUE THREAD

**Issue by Apolly007** [Pure-L0G1C/Loki#13]
im getting this error when I try to execute it

root@kaliRoman:/media/root/46DD-8D02/Windows/programs/botnet/Loki-master# python loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "/media/root/46DD-8D02/Windows/programs/botnet/Loki-master/lib/server/server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const
root@kaliRoman:/media/root/46DD-8D02/Windows/programs/botnet/Loki-master# python2 loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "/media/root/46DD-8D02/Windows/programs/botnet/Loki-master/lib/server/server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const
root@kaliRoman:/media/root/46DD-8D02/Windows/programs/botnet/Loki-master# python3 loki.py
Traceback (most recent call last):
  File "loki.py", line 10, in <module>
    from flask import Flask, render_template, request, session, jsonify, redirect, url_for
ModuleNotFoundError: No module named 'flask'

I've tried python, python2 and python3 didn't work
I've got python 2.7
(I've pasted everything that's written)
thx for helping....

**Comment by EZRAIDv2** [comment]
Use ```pip3 install flask``` in terminal.
