### ISSUE TITLE
It will not let me login with given credentials

### ISSUE THREAD

**Issue by Chacon12** [Pure-L0G1C/Loki#14]

**Comment by Chacon12** [comment]
Im on Parrot OS and when making the payload it will prompt me to this : 
1) MS Word
2) MS Excel
3) MS Powerpoint

Select an icon option: 3
Traceback (most recent call last):
  File "builder.py", line 142, in <module>
    if not option.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

**Comment by Pure-L0G1C** [comment]
It’s to be compiled in Windows

**Comment by richardhash** [comment]
1) MS Word
2) MS Excel
3) MS Powerpoint

Select an icon option: 3
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Loki\builder\builder.py", line 154, in <module>
    executor.start()
  File "C:\Users\Administrator\Desktop\Loki\builder\builder.py", line 116, in start
    self.compile_bot()
  File "C:\Users\Administrator\Desktop\Loki\builder\builder.py", line 87, in compile_bot
    self.write_template(self.bot_template, self.bot_py_temp, _dict)
  File "C:\Users\Administrator\Desktop\Loki\builder\builder.py", line 72, in write_template
    for _data in File.read(template, False):
  File "C:\Users\Administrator\Desktop\Loki\builder\lib\file.py", line 12, in read
    with open(file, 'rb' if _bytes else 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'bot\\template_bot.py'

**Comment by richardhash** [comment]
Do i need to have MS program before it could compile, since i am using the icons.
