### ISSUE TITLE
???

### ISSUE THREAD

**Issue by ColeShelly** [Pure-L0G1C/Loki#2]
652 INFO: PyInstaller: 3.3.1
652 INFO: Python: 3.6.6
654 INFO: Platform: Linux-4.17.0-kali3-686-pae-i686-with-Kali-kali-rolling-kali-rolling
655 INFO: wrote /root/Desktop/Loki/builder/Test1.spec
660 INFO: UPX is available.
662 INFO: Extending PYTHONPATH with paths
['/root/Desktop/Loki/builder/bot', '/root/Desktop/Loki/builder']
662 INFO: checking Analysis
662 INFO: Building Analysis because out00-Analysis.toc is non existent
663 INFO: Initializing module dependency graph...
669 INFO: Initializing module graph hooks...
671 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "/usr/lib/python3.6/pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/lib/python3.6/pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "/usr/lib/python3.6/inspect.py", line 41, in <module>
    import linecache
  File "/usr/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "/usr/lib/python3.6/pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/lib/python3.6/pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "/usr/lib/python3.6/inspect.py", line 41, in <module>
    import linecache
  File "/usr/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
8363 INFO: running Analysis out00-Analysis.toc
8424 INFO: Caching module hooks...
8431 INFO: Analyzing /root/Desktop/Loki/builder/bot/Test1.py
9679 INFO: Processing pre-safe import module hook   six.moves
12575 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/building/build_main.py", line 415, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1351, in run_script
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2420, in _safe_import_hook
    edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1441, in import_hook
    target_module, target_attr_names):
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1729, in _import_importable_package_submodules
    attr_name, submodule_name, package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1425, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1638, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1424, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1576, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2031, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2816, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1424, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1576, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2031, in _load_module
    m = self._load_package(fqname, pathname, packagepath)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2816, in _load_package
    self._load_module(fqname, fp, buf, stuff)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1424, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1576, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1424, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1576, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 271, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1993, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1425, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1638, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/depend/analysis.py", line 260, in _safe_import_module
    hook_module.pre_safe_import_module(hook_api)
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py", line 31, in pre_safe_import_module
    for real_module_name, six_module_name in real_to_six_module_name.items():
AttributeError: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "builder.py", line 98, in <module>
    executor.start()
  File "builder.py", line 82, in start
    self.compile_bot()
  File "builder.py", line 68, in compile_bot
    for data in File.read(self.bot_compiled):
  File "/root/Desktop/Loki/builder/lib/file.py", line 11, in read
    with open(file, 'rb' if _bytes else 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dist/Test1.exe'

**Comment by m-henderson** [comment]
please provide steps so that we can reproduce your issue.

**Comment by Pure-L0G1C** [comment]
It seems like he is using Linux to generate an executable. I'll have to make the generator work with Wine to fix this issue on Linux.

**Comment by ColeShelly** [comment]
@Pure-L0G1C Yeah I'm using Kali Linux (Latest)
