### ISSUE TITLE
unable to build agent

### ISSUE THREAD

**Issue by tehseensagar** [Pure-L0G1C/Loki#21]
I'm trying to build an agent for loki but failed to build

python3.7 -i x.x.x.x -p 443 -n mypayload -t exe 

`Traceback (most recent call last):
  File "agent/builder.py", line 172, in <module>
    executor.start()
  File "agent/builder.py", line 134, in start
    self.compile_bot()
  File "agent/builder.py", line 93, in compile_bot
    self.write_template(self.bot_template, self.bot_py_temp, _dict)
  File "agent/builder.py", line 77, in write_template
    for _data in File.read(template, False):
  File "/opt/Loki-master/agent/lib/file.py", line 12, in read
    with open(file, 'rb' if _bytes else 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'bot/template_bot.py'

I'm using Ubuntu 16.04 .

Regards
`

**Comment by Pure-L0G1C** [comment]
Try changing directories into agent folder
