### ISSUE TITLE
error

### ISSUE THREAD

**Issue by emans841** [Pure-L0G1C/Loki#4]
python loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "/root/Desktop/Loki/lib/server/server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const

please help

**Comment by m-henderson** [comment]
@emans841 could you provide complete steps you used in order to generate this error?

**Comment by Codeliquid85** [comment]
After pip install -r requirements and configuring const.py and trying to start looking.py with python loki.py is when that error comes up.

**Comment by Codeliquid85** [comment]
Sorry autocorrect loki.py

**Comment by edgaru** [comment]
Do you run it with python 3.6?

**Comment by Codeliquid85** [comment]
I'll have to check when I get in front of my computer should it be 3.6 or a different version

**Comment by Codeliquid85** [comment]
It's version 2.75

**Comment by Codeliquid85** [comment]
Running with python3 fixed it
