### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by honkhewins** [Pure-L0G1C/Loki#48]
Python version: 3.8.10

the error i have: 

Traceback (most recent call last):
  File "loki.py", line 10, in <module>
    from lib.server.server import Server
  File "C:\Users\JakePC\Desktop\Stuff\Quaritine Place\Loki-master\Loki-master\lib\server\server.py", line 11, in <module>
    from OpenSSL import crypto
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenSSL\crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by honkhewins** [comment]
I tried manually installing open SSL and still same error
![image](https://user-images.githubusercontent.com/70330761/234869442-a75c9b6f-2534-4b5c-bf07-0261526ae72a.png)

**Comment by EvgenyGor** [comment]
similar problem, how to solve it?

**Comment by Jephteman** [comment]
the problem is not in the program's source code but in one of its dependencies

**Comment by mrx0me** [comment]
the problem is not in the program's source code but in one of its dependencies.

As version 39.0.0 presented this bug, downgrading the cryptography package solves this, without purging or touching your OS.
pip install cryptography==38.0.4 to downgrade from 39.0.0 which presented this error
