### ISSUE TITLE
#FileNotFoundError: [WinError 2] The System cannot find the  file specified 

### ISSUE THREAD

**Issue by VirusEmp** [Pure-L0G1C/Loki#6]
#After running all procedures as follows
pip install -r requirements.txt
#went all good
then started my server side with http://127.0.0.1:5000
#went good
python loki.py
#successfully started
###this below is where my issue is..
##NB i am using python3.7
C:\Users\3333333\Desktop\Loki-master\builder>python builder.py -i 127.0.0.1 -p 8080 -n Update -t exe
Traceback (most recent call last):
  File "builder.py", line 98, in <module>
    executor.start()
  File "builder.py", line 82, in start
    self.compile_bot()
  File "builder.py", line 66, in compile_bot
    self.write_template(self.bot_template, self.bot_py_temp, _dict)
  File "builder.py", line 56, in write_template
    self.compile_file(py_temp)
  File "builder.py", line 47, in compile_file
    Popen(cmd.split()).wait()
  File "C:\Users\3333333\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\3333333\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\3333333\Desktop\Loki-master\builder>
#Please any fix for this issue or is there an OS that can run this smoothly without errors
#tried parrot still having errors now using windows still having errors
Thank You

**Comment by Pure-L0G1C** [comment]
Thanks for letting me know, I’ll look into it

**Comment by Pure-L0G1C** [comment]
Try using Python3.6

**Comment by VirusEmp** [comment]
#Thank you it worked perfectly
exe Bot built successfully
#then am having an issue testing it on my test pc
#firstly i couldnt send it via email but i got around to using an autodownload link which worked perfectly
#now running the exe file as admin it says
The program can't start because api-ms-win-crt-math-l1-1-o.dll is missing from your computer.try reisnstalling the program to fix this
error loading python dll 
Load libary the specified module could not be found.
#i knw this error is cos the iles used in building the bot are not in the test machine.
#which we all know not every victim would have python3.6 running
#suggestion: if the bot could allow the user to choose what basic files to build with or for ..eg. Arch and Os.
#Thank you for your help.look forward to better upgrades
#AWesome script

**Comment by Pure-L0G1C** [comment]
If you’re using a VM, it might be your VM doesn’t have that dll file

**Comment by VirusEmp** [comment]
Thanks for the reply ..am not using a VM..i have 2 pc
built the bot on one which is windows 10 and tried attcking my second pc which is windows 8.
but i think i found the solution..the dll file is missing from the system..cos i tried another simle script i wrote for a task and it also didnt start up.
Thank you.
