### ISSUE TITLE
fixit

### ISSUE THREAD

**Issue by albinlaci** [Pure-L0G1C/Loki#8]
C:\Users\Entertaiment\Desktop\Loki-master>python loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "C:\Users\Entertaiment\Desktop\Loki-master\lib\server\server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const

**Comment by albinlaci** [comment]
it does not work

**Comment by Pure-L0G1C** [comment]
What Python at you using?

**Comment by Pure-L0G1C** [comment]
You Python 3.6+

**Comment by albinlaci** [comment]
it works thk
